name: AliyunOSS
on: [push]
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Project
        run: npm install && npm run build
        working-directory: web
      - name: Deploy OSS
        uses: taixw2/deploy-aliyun-oss@1
        with:
          # aliyun config
          region: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.BUCKET }}
          secure: true
          # deploy config
          entry: public/**/* # glob pattern
          remote-dir: /web/public
          path-rewrite: ^public/